name: Docker Image CI for GHCR

on:
    push

jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: npm install
              run: npm ci
            - name: run the unit tests
              run: npm test
            - name: Build and push the image
              run: |
                docker login --username aniket2468 --password ${{secrets.ACCESS_TOKEN}} ghcr.io
                docker build -t ghcr.io/aniket2468/arithmetic-service:latest --file Dockerfile .  
                docker push ghcr.io/aniket2468/arithmetic-service:latest 
            - name: Publish the image to azure container registry
              run: |
                docker login --username practicum15 --password ${{secrets.AZURE_CONTAINER_REGISTRY}} practicum15aa.azurecr.io
                docker tag ghcr.io/aniket2468/arithmetic-service:1 practicum15aa.azurecr.io/arithmetic-service:1
                docker push practicum15aa.azurecr.io/arithmetic-service:1